//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocStudiosMVCProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocStudiosMVCProject.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets Tell You about Us .
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Our clients.
        /// </summary>
        public static string ClientsDis {
            get {
                return ResourceManager.GetString("ClientsDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our clients.
        /// </summary>
        public static string ClientsTitle {
            get {
                return ResourceManager.GetString("ClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Valid Email Address.
        /// </summary>
        public static string CustomerEmailErr {
            get {
                return ResourceManager.GetString("CustomerEmailErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone Number.
        /// </summary>
        public static string CustomerPhoneNum {
            get {
                return ResourceManager.GetString("CustomerPhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Valid Email Phone Number.
        /// </summary>
        public static string CustomerPhoneNumErr {
            get {
                return ResourceManager.GetString("CustomerPhoneNumErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Our Services.
        /// </summary>
        public static string HomeBtn {
            get {
                return ResourceManager.GetString("HomeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are create A wanderfull Web Sites And Web Design.
        /// </summary>
        public static string HomeDis {
            get {
                return ResourceManager.GetString("HomeDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Are Roch Stodio.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Name.
        /// </summary>
        public static string NameErr {
            get {
                return ResourceManager.GetString("NameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can order the service that you choosen from here.
        /// </summary>
        public static string OrderDis {
            get {
                return ResourceManager.GetString("OrderDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNu {
            get {
                return ResourceManager.GetString("OrderNu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string OrderSummary {
            get {
                return ResourceManager.GetString("OrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Form.
        /// </summary>
        public static string OrderTitle {
            get {
                return ResourceManager.GetString("OrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Our Portfolio.
        /// </summary>
        public static string PortfolioDis {
            get {
                return ResourceManager.GetString("PortfolioDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Our Portfolio.
        /// </summary>
        public static string PortfolioTitle {
            get {
                return ResourceManager.GetString("PortfolioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Now.
        /// </summary>
        public static string ServicesBtn {
            get {
                return ResourceManager.GetString("ServicesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Our Services We Provide A sevral Types of Services And You Can Order it Now !.
        /// </summary>
        public static string ServicesDis {
            get {
                return ResourceManager.GetString("ServicesDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Our Services.
        /// </summary>
        public static string ServicesTitle {
            get {
                return ResourceManager.GetString("ServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Our Team.
        /// </summary>
        public static string TeamDis {
            get {
                return ResourceManager.GetString("TeamDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met Our Team.
        /// </summary>
        public static string TeamTile {
            get {
                return ResourceManager.GetString("TeamTile", resourceCulture);
            }
        }
    }
}
